version: "3.3"

services:
  notification_api:
    build: "."
    tty: true
    ports:
      - 0.0.0.0:9999:9999
    environment:
      - NODE_ENV=development
      - APP_PORT=9999
      - APP_SECRET=ABCDEF

      - MONGO_URL=mongodb://notification_mongodb:27017
      - MONGO_DB=notification_db

      - SENDER_PHONE_NUMBER=+55 99123-1233
      - SENDER_EMAIL=no-reply@gmail.com

    volumes:
      - .:/opt/app
    networks:
      - notification_local_network

  notification_mongodb:
    environment:
      - MONGO_DB=notification_db
    image: bitnami/mongodb:latest
    ports:
      - 0.0.0.0:27017:27017
    networks:
      - notification_local_network

networks:
  notification_local_network:
    driver: bridge
