@host = http://localhost:3000

@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZmZmOWFjOTYtZWNkNy00NzMzLTkzMDAtNDdjMTVjYzM5NTQwIiwiZW1haWwiOiJzdXBvcnRlQHZlcmdyb3VwLmRldiIsIm5hbWUiOiJTdXBvcnRlIiwicm9sZXMiOltdfSwiaWF0IjoxNjc1MTg3ODMyLCJleHAiOjE2NzUyNzQyMzIsInN1YiI6ImZmZjlhYzk2LWVjZDctNDczMy05MzAwLTQ3YzE1Y2MzOTU0MCJ9.z-vRaCENR7B9toRE8DkKR8hWVHvyHg2iKY5QyiS8QI4

# SESSION

### Authenticate

POST {{host}}/sessions
content-type: application/json

{
  "email": "contato@williansfranco.dev",
  "password": "123mudar"
}

### Renew token

POST {{host}}/sessions/renew
content-type: application/json
Authorization: {{token}}

{
  "id": "f99d6fee-37d5-4422-951d-f5690b2e3626",
  "email": "suporte@vergroup.dev",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiZjk5ZDZmZWUtMzdkNS00NDIyLTk1MWQtZjU2OTBiMmUzNjI2IiwiZW1haWwiOiJzdXBvcnRlQHZlcmdyb3VwLmRldiIsIm5hbWUiOiJNYXN0ZXIiLCJyb2xlIjp7fX0sImlhdCI6MTY3NTA2OTUwMSwiZXhwIjoxNjc1MTU1OTAxLCJzdWIiOiJmOTlkNmZlZS0zN2Q1LTQ0MjItOTUxZC1mNTY5MGIyZTM2MjYifQ.STbBaWAqENVYr0U4xWNIEydlM34qbdUkkZVcYUV9m4c",
  "renewToken": "04dd5725064cc9dcfd3d4f65bab12c5c11a960c4e3ea85d0a99bb3c779006d16087d3115c373c7e3cb5901e10077cd8b4a82f85c25081748901b52c18b9689f64d93349fc774975664bf3a9a14c57967fb03c131d63b42251228bdf6ea6f7b0ed7f5fd51e083ad2ebdd16486c1d23b1c781d1b6c632b76765e8125a113403599149aed290283b4d48f252feeb0c8ab4e6322454f768dcb965a6e047b735747ebe049ab48bf4e587c30dfa8f20227ccbaf4e7ffca16bbb75a96c66ad2b159fd9a008aecc6dcf2f3d83aac9eced28a756c882f5b86a53f80e413a3"
}

# USER

### Create user

POST {{host}}/users
content-type: application/json
Authorization: {{token}}

{
  "name": "Suporte",
  "email": "suporte@vergroup.dev",
  "password": "123mudar",
  "role_id": "0cce7ea7-6350-46c5-b424-80173ab459da"
}

### Get users

GET {{host}}/users/list
content-type: application/json
Authorization: {{token}}

### Get user

GET {{host}}/users/id/23df5390-38ab-4d5c-a60f-821258106ea7
content-type: application/json
Authorization: {{token}}

### Update user

PUT {{host}}/users/9e76f2fc-1e48-49ef-b342-58b775d37611
content-type: application/json
Authorization: {{token}}

{
  "name": "Suporte 2"
}

### Delete user

DELETE {{host}}/users/9e76f2fc-1e48-49ef-b342-58b775d37611
content-type: application/json
Authorization: {{token}}

# MODULE

### Create module

POST {{host}}/modules
content-type: application/json
Authorization: {{token}}

{
  "name": "Module Test"
}

### List modules

GET {{host}}/modules
content-type: application/json
Authorization: {{token}}

### Show module

GET {{host}}/modules/7612a025-9584-46d6-af25-45c33dcfbd0d
content-type: application/json
Authorization: {{token}}

### Update module

PUT {{host}}/modules/557821f4-359d-4d84-b56a-0e189faed1a7
content-type: application/json
Authorization: {{token}}

{
  "name": "Module Test 2"
}

### Delete module

DELETE {{host}}/modules/557821f4-359d-4d84-b56a-0e189faed1a7
content-type: application/json
Authorization: {{token}}

# PERMISSION

### Create permission

POST {{host}}/permissions
content-type: application/json
Authorization: {{token}}

{
  "name": "Permission Test"
}

### List permissions

GET {{host}}/permissions/list
content-type: application/json
Authorization: {{token}}

### Show permission

GET {{host}}/permissions/id/374d9219-51dc-46a2-be68-5cb333b7355b
content-type: application/json
Authorization: {{token}}

### Update permission

PUT {{host}}/permissions/655c161d-dc6a-4e79-8d0b-6325392fd2f9
content-type: application/json
Authorization: {{token}}

{
  "name": "Permission Test 2"
}

### Delete permission

DELETE {{host}}/permissions/8d07521e-3fb9-4f38-9a54-432889eed35a
content-type: application/json
Authorization: {{token}}

# ROLE

### Create role

POST {{host}}/roles
content-type: application/json
Authorization: {{token}}

{
  "name": "Administrador",
  "isAdmin": true,
  "isSystem": true
}

### List roles

GET {{host}}/roles/list
content-type: application/json
Authorization: {{token}}

### Show role

GET {{host}}/roles/id/0cce7ea7-6350-46c5-b424-80173ab459da
content-type: application/json
Authorization: {{token}}

### Update role

PUT {{host}}/roles/0cce7ea7-6350-46c5-b424-80173ab459da
content-type: application/json
Authorization: {{token}}

{
  "name": "Administrador 2"
}

### Delete role

DELETE {{host}}/roles/fc74b40d-feda-49a4-b5dd-e956903f17e8
content-type: application/json
Authorization: {{token}}

# ROLE_PERMISSION

### Create role_permission

POST {{host}}/role_permissions
content-type: application/json
Authorization: {{token}}

{
  "role_id": "0cce7ea7-6350-46c5-b424-80173ab459da",
  "permission_id": "b4f655a9-0817-4f80-9b96-e45f872b1599",
  "module_id": "666f613e-e76d-4ad9-bd4a-3caea7482132"
}

### Show role_permission by role, permission and module

GET {{host}}/role_permissions/role/0cce7ea7-6350-46c5-b424-80173ab459da/permission/b4f655a9-0817-4f80-9b96-e45f872b1599/module/666f613e-e76d-4ad9-bd4a-3caea7482132
content-type: application/json
Authorization: {{token}}

### List role_permission

GET {{host}}/role_permissions/list
content-type: application/json
Authorization: {{token}}

### List roles related of role_permission

GET {{host}}/role_permissions/role/0cce7ea7-6350-46c5-b424-80173ab459da
content-type: application/json
Authorization: {{token}}

### Update role_permission

PUT {{host}}/role_permissions/role/0cce7ea7-6350-46c5-b424-80173ab459da/permission/b4f655a9-0817-4f80-9b96-e45f872b1599/module/666f613e-e76d-4ad9-bd4a-3caea7482132
content-type: application/json
Authorization: {{token}}

{
  "role_id": "0cce7ea7-6350-46c5-b424-80173ab459da",
  "permission_id": "b4f655a9-0817-4f80-9b96-e45f872b1599",
  "module_id": "666f613e-e76d-4ad9-bd4a-3caea7482132"
}

### Delete role_permission

DELETE {{host}}/role_permissions/role/0cce7ea7-6350-46c5-b424-80173ab459da/permission/b4f655a9-0817-4f80-9b96-e45f872b1599/module/666f613e-e76d-4ad9-bd4a-3caea7482132
content-type: application/json
Authorization: {{token}}


### Create pre-register
POST {{host}}/pre-register
content-type: application/json
Authorization: {{token}}

{
  "name": "Test User One",
  "email": "test@gmail.com",
  "password": "123mudar",
  "cell_phone": "15 99123-3212",
  "cpf": "123.123.322-02"
}

### List pre-register

GET {{host}}/pre-register/list
content-type: application/json
Authorization: {{token}}

### Show pre-register

GET {{host}}/pre-register/id/63dce664adcf5402fde02132
content-type: application/json
Authorization: {{token}}

### Update pre-register

PUT {{host}}/pre-register/63dce664adcf5402fde02132
content-type: application/json
Authorization: {{token}}

{
  "approved": true,
  "user_id": "655c161d-dc6a-4e79-8d0b-6325392fd2f9"
}


### Delete pre-register

DELETE  {{host}}/pre-register/63dce664adcf5402fde02132
content-type: application/json
Authorization: {{token}}
